config/routes.rb
Blog::Application.routes.draw do

  match Blog::CLEAR_CACHE_PATH => 'pages#clear_cache'

  match 'pages/recent_posts' => 'pages#recent_posts'
  match 'pages/:page' => 'pages#index'

  resources :pages
  resources :contact, only: [:create]
  match 'contact' => 'contact#new'

  resources :sessions
  resources :comments, only: [:create, :destroy]
  
  resources :users, only: [:show]

  root :to => 'pages#index'
  
  namespace :admin do
    root to: "pages#index"
    match 'posts' => "pages#index", type: :post
    get 'pages' => "pages#index", type: :page
    resources :pages
    resources :comments
    resources :menus
  end

  match 'login' => 'sessions#new', as: :login
  match 'logout' => 'sessions#destroy', as: :logout

  match 'search' => 'pages#search', as: :search

  match 'archives' => 'pages#archives', as: :archives
  match 'feed' => 'pages#index', as: :feed
  match ':slug' => 'pages#show', as: :page

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment, :name, :page_id, :url, :email
  belongs_to :page, counter_cache: true

  validates :name, presence: true, length: { in: 2..255 }
  validates :email, presence: true, format: { with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
  validates :url, allow_blank: true, format: { with: URI::regexp(%w(http https)) }
  validates :comment, presence: true
end

app/models/contact.rb
class Contact
  include ActiveAttr::Model

  attribute :name
  attribute :email
  attribute :message

  validates :name, presence: true, length: { in: 2..255 }
  validates :email, presence: true, format: { with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
  validates :message, presence: true, length: { minimum: 20 }
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :order, :path, :title
end

app/models/page.rb
class Page < ActiveRecord::Base

  acts_as_taggable

  attr_accessible :body, :has_comments, :title, :slug, :page_type, :is_published, :tag_list

  has_many :comments

  scope :published, where(is_published: true)
  scope :posts, where(page_type: 'post')
  scope :pages, where(page_type: 'page')
  scope :published_posts, published.posts

  validates :title, presence: true, length: { in: 3..255 }
  validates :slug, presence: true, uniqueness: true, length: { in: 3..255 }
  validates :body, presence: true, length: { minimum: 100 }

  def self.tags_to_a
    tag_counts.collect { |tag| tag.name }
  end

  def self.text_search(query)
    if query.present?
      search(body: query).published
    else
      scoped
    end
  end

  def previous
    Page.published_posts.where("id < ?", id).order('id ASC').last
  end

  def next
    Page.published_posts.where("id > ?", id).order('id ASC').first
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  validates :email, uniqueness: true, presence: true, format: { with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_url, alert: 'Not authorized' if current_user.nil?
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  after_filter :prepare_unobtrusive_flash
  cache_sweeper :page_sweeper

  before_filter :authorize, only: [:destroy]

  def create
    page = Page.find(params[:comment][:page_id])

    if params[:remember_me]
      cookies[:comment_name]  = params[:comment][:name]
      cookies[:comment_email] = params[:comment][:email]
      cookies[:comment_url]   = params[:comment][:url]
    end

    # Clear cache
    PageSweeper.instance.sweep(page)

    @comment = page.comments.create params[:comment]
    
    # Send email
    CommentMailer.new_comment(@comment).deliver

    render partial: 'comment', locals: { comment: @comment }
  end

  def destroy
    @comment = Comment.find(params[:id])
    @id = params[:id]

    PageSweeper.instance.sweep(@comment.page)

    @comment.destroy
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  after_filter :prepare_unobtrusive_flash

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if @contact.valid?
      ContactMailer.new_contact(@contact).deliver
      redirect_to root_url, notice: "Message sent! I will get back to you as soon as humanly possible."
    else
      render 'new'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  caches_page :index, :show, :archives if Blog.cache == :page
  caches_action :index, :show, :archives if Blog.cache == :action

  def index
    @pages = Page.published_posts.order('created_at DESC').paginate(:page => params[:page], :per_page => Blog::POSTS_PER_PAGE)
    respond_to do |format|
      format.html
      format.atom
    end
  end

  def show
    @page = Page.published.find_by_slug(params[:slug])
    return redirect_to root_path unless @page
    @previous_page = @page.previous
    @next_page = @page.next
    @related_posts = @page.find_related_tags.limit(4)
    @comment = Comment.new
  end

  def archives
    posts = Page.published_posts.order('created_at DESC').select("id, title, slug, extract(month from created_at) as month, extract(year from created_at) as year")
    @posts = {}

    posts.each do |post|
      date = "#{Date::MONTHNAMES[post.month.to_i]} #{post.year}"
      @posts[date] ||= []
      @posts[date] << post
    end

  end

  def search
    @posts = Page.text_search(params[:query]).paginate(:page => params[:page], :per_page => Blog::POSTS_PER_SEARCH)
  end

  def recent_posts
    
  end

  def clear_cache
    Rails.cache.clear
    render text: 'cache cleared'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  after_filter :prepare_unobtrusive_flash
  
  def new
    redirect_to root_url if current_user
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      cookies[:logged_in] = true
      redirect_to root_url, notice: 'Logged in.'
    else
      flash.now.alert = "Email or password is incorrect."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    cookies[:logged_in] = false
    redirect_to root_url, notice: 'Logged out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  after_filter :prepare_unobtrusive_flash
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new params[:user]
    if @user.save
      redirect_to root_url, notice: 'Thanks for signing up.'
    else
      render 'new'
    end
  end

  def show
    
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, :lexer => language)
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(:hard_wrap => true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :tables => true,
      :strikethrough => true,
      :lax_html_blocks => true,
      :superscript => true,
      :filter_html => true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end

  def title_for_header
    if Blog::TITLE.include? '.'
      return "<span class='tld'>#{Blog::TITLE.split('.').first}</span><span class='suffix'>.#{Blog::TITLE.split('.').last}</span>"
    else
      return "<span class='tld'>#{Blog::TITLE}</span>"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/pages/_form.html.slim
= simple_form_for [:admin, @page] do |f|
  - if @page.errors.any?
    #error_explanation
      h2 = "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - @page.errors.full_messages.each do |message|
          li = message

  = f.input :title, input_html: { class: 'title' }
  = f.input :slug, input_html: { class: 'slug' }
  = f.input :page_type, as: :hidden, input_html: { value: params[:type] || @page.try(:page_type) }
  = f.input :has_comments if params[:type] == 'post' || @page.try(:page_type) == 'post'
  = f.input :is_published
  = f.input :tag_list if params[:type] == 'post' || @page.try(:page_type) == 'post'
  #epiceditor
  = f.input :body, label: false
  .actions 
    = f.submit 'Save Page', class: 'btn'
    | &nbsp;
    = link_to 'Back', admin_pages_path

#tag-list data-tags='#{Page.tags_to_a}'

app/views/admin/pages/edit.html.slim
h1 Editing #{@page.page_type.capitalize}

== render 'form'

app/views/admin/pages/index.html.slim
h1 Listing #{@type.to_s.pluralize}
table
  tr
    th Title
    th Last Updated
    th Published
    th.actions colspan="2" Actions

  - @pages.each do |page|
    tr
      td.title = link_to "#{page.title} <i class='icon-external-link'></i>".html_safe, admin_page_path(page), target: '_blank'
      td = page.updated_at.to_formatted_s(:short)
      td = page.is_published
      td.actions.edit = link_to 'edit', edit_admin_page_path(page), class: 'btn'
      td.actions.delete = link_to 'delete', [:admin, page], :confirm => 'Are you sure?', :method => :delete, class: 'btn'

br

= link_to "New #{@type}", new_admin_page_path(type: params[:type]), class: 'btn'

app/views/admin/pages/new.html.slim
h1 New #{params[:type].to_s.capitalize}

== render 'form'

app/views/admin/pages/show.html.slim
= render 'pages/page', page: @page

= link_to 'Edit', edit_admin_page_path(@page), class: 'btn'
| &nbsp;
= link_to 'Back', admin_pages_path

app/views/layouts/_dynamic_header.html.slim
li.admin.grav = gravatar_image_tag current_user.email, gravatar: { size: 20 }
li.admin = link_to 'admin', '/admin'
li.admin = link_to 'logout', '/logout', 'data-no-turbolink' => true

app/views/layouts/_recent_posts.html.slim
- Page.published_posts.order('created_at DESC').limit(Blog::RECENT_POSTS).each do |page|
  li = link_to page.title, page_path(page.slug)

app/views/layouts/admin.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title = content_for?(:title) ? yield(:title) + " · #{Blog::TITLE}" : Blog::TITLE
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "admin", :media => "all"

  body.admin
    .top-stripe
    .header
      .container
        .logo
          a href="/admin"
            == title_for_header
        ul
          li = link_to 'posts', '/admin/posts'
          li = link_to 'pages', '/admin/pages'
          li = link_to 'comments', admin_comments_path
          li = link_to 'menu', admin_menus_path
          li = gravatar_image_tag current_user.email, gravatar: { size: 20 }
          li = link_to 'home', root_path
          li = link_to 'logout', '/logout'

    .container
      - if notice
        p.notice
          | <a href="#" class="close-btn">×</a>
          = notice
      - if alert
        p.alert
          | <a href="#" class="close-btn">×</a>
          = alert
      = yield

      .breaker

    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "admin"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"

    link href="#{Blog::RSS}" rel="alternate" title="#{Blog::TITLE}" type="application/atom+xml"
    title = content_for?(:title) ? yield(:title) + " · #{Blog::TITLE}" : Blog::TITLE
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    
  body
    .top-stripe
    .header
      .container
        .logo
          a href="/"
            == title_for_header
        i.iconf-lamp
        .search
          form method="get" action="#{search_path}"
            input name="query" type="search" placeholder="search..." onfocus="this.placeholder = ''" onblur="this.placeholder = 'search...'" value="#{params[:query]}"

        ul.main-nav

          li = link_to 'about', '/about'
          li = link_to 'work', '/work'
          li = link_to 'archives', '/archives'
          li = link_to 'contact', '/contact'
          li = link_to 'rss', Blog::RSS


    .container
      .main
        ul.small
        = yield
      .side-bar
        .side
          .top-btn <i class="icon-caret-up"></i>
          h4.name = Blog::NAME
          p.location <i class="icon-map-marker"></i> #{Blog::LOCATION}
          = gravatar_image_tag Blog::EMAIL, gravatar: { size: 60 }
          p.about = Blog::BLURB
          ul.links
            li
              a href="http://www.github.com/#{Blog::GITHUB}" <i class="icon-github"></i> GitHub
            li
              a href="http://www.twitter.com/#{Blog::TWITTER}" <i class="icon-twitter"></i> Twitter
            li
              a href="http://www.linkedin.com/in/#{Blog::LINKEDIN}" <i class="icon-linkedin"></i> LinkedIn

          h4.recent <i class="icon-time"></i> Recent Posts
          ul.recent-posts

      .breaker
      div style="position: absolute; left: 50%;"
        div style="position: relative; left: -50%"
          a.sm-top-btn.top-btn <i class="icon-caret-up"></i>

    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    javascript:
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', '#{Blog::GOOGLE_ANALYTICS}']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

app/views/pages/_page.html.slim
- if params[:action] == 'show' && page.page_type == 'post'
  - if @previous_page
    .prev-preview
      strong = @previous_page.title
      p == strip_tags(markdown(@previous_page.body)).truncate(100)
    .prev
      = link_to 'Previous', page_path(@previous_page.slug)
  -if @next_page
    .next-preview
      strong = @next_page.title
      p == strip_tags(markdown(@next_page.body)).truncate(100)
    .next 
      = link_to 'Next', page_path(@next_page.slug)

.post
  - if page.page_type == 'post'
    .comment-count
      i.icon-comments
      span.count = page.comments_count || 0
    .date <i class="icon-calendar"></i> #{page.created_at.to_formatted_s(:proper)}
  .title
    - if params[:action] == 'index'
      = link_to page.title, page_path(page.slug)
    - else
      = page.title
  .body
    = markdown page.body

  = render(partial: 'pages/tweet', locals: { page: page }) if params[:action] == 'show' && page.page_type == 'post'

app/views/pages/_tweet.html.slim
.tweet
  a onclick="return tweet()" href="#" <i class="icon-twitter"></i> Tweet this post if you found it useful
  javascript:
    delete tweet;
    var tweet = function () {
      var left = (screen.width/2)-(600/2);
      var top = (screen.height/2)-(300/2);
      window.open(
        "https://twitter.com/share?via=andruu&text=Check out #{page.title}&url=#{page_url(page.slug)}",
        "Tweet Post", "width=600,height=300,top="+top+",left="+left+""
      );
      return false;
    }

app/views/pages/archives.html.slim
- content_for :title do
 - 'Archives'

.post
  h1.title Archives
  - @posts.each do |month|
    h3 = month.first
    ul
      - month[1].each do |post|
        li = link_to post.title, page_path(post.slug)
    

app/views/pages/index.html.slim
= render partial: 'page', collection: @pages
= will_paginate @pages, page_links: false

app/views/pages/recent_posts.js.erb
window.cachedRecentPosts = '<%= j render("layouts/recent_posts") %>';
$('ul.recent-posts').append(window.cachedRecentPosts);

app/views/pages/search.html.slim
.post
  h1.title Search results for #{params[:query]}
  - @posts.each do |post|
    .search-result
      strong
        = link_to post.title, page_path(post.slug)

      p == highlight(excerpt(strip_tags(markdown(post.body)), params[:query], radius: 60), params[:query])

= will_paginate @posts, page_links: false

app/views/pages/show.html.slim
- content_for :title do
 - @page.title

= render @page
- if @page.page_type == 'post' && @related_posts.to_a.size > 0
  .related-post-box
    h3 <i class="icon-tags"></i> Related Posts
    - @related_posts.each do |post|
      .related-post class="#{cycle('first', 'second', 'third', 'fourth')}"
        strong.link = link_to post.title, page_path(post.slug)
        p.info
          = post.created_at.to_formatted_s(:proper)
          | &nbsp; &middot; &nbsp;<i class="icon-comments"></i> #{post.comments_count || 0}
        p.start == strip_tags(markdown(post.body)).truncate(100, omission: '... (continued)')

- if @page.has_comments
  .comments#comments class="#{(@related_posts.to_a.size == 0) ? 'no-related' : nil}"
    h3.title <span class="count">#{@page.comments_count || 0}</span> #{'Comment'.pluralize(@page.comments_count)}
    .comment-added
      | Comment successfully added. <a href="#" class="bottom-btn">View comment</a>.
      | <a href="#" class="close-btn">×</a>
    - if @page.created_at < 2.weeks.ago
      .comment-form
        p Comments are now closed for this article.
    - else
      .comment-form
        = simple_form_for @comment, remote: true, html: { 'data-update' => '.comments' } do |f|
          = f.input :page_id, as: :hidden, input_html: { value: @page.id }
          = f.input :name, label: false, placeholder: 'name'
          = f.input :email, label: false, placeholder: 'email'
          = f.input :url, label: false, placeholder: 'http://'
          = f.input :comment, label: false, placeholder: 'leave a message...'
          = f.submit 'Post Comment', class: 'btn add-comment'
          .remember-me
            label
              = check_box_tag 'remember_me', 1, true
              span Remember Me?

    = render partial: 'comments/comment', collection: @page.comments.order('created_at ASC')