config/routes.rb
Blog::Application.routes.draw do

  match Blog::CLEAR_CACHE_PATH => 'pages#clear_cache'

  match 'pages/recent_posts' => 'pages#recent_posts'
  match 'pages/:page' => 'pages#index'

  resources :pages
  resources :contact, only: [:create]
  match 'contact' => 'contact#new'

  resources :sessions
  resources :comments, only: [:create, :destroy]
  
  resources :users, only: [:show]

  root :to => 'pages#index'
  
  namespace :admin do
    root to: "pages#index"
    match 'posts' => "pages#index", type: :post
    get 'pages' => "pages#index", type: :page
    resources :pages
    resources :comments
    resources :menus
  end

  match 'login' => 'sessions#new', as: :login
  match 'logout' => 'sessions#destroy', as: :logout

  match 'search' => 'pages#search', as: :search

  match 'archives' => 'pages#archives', as: :archives
  match 'feed' => 'pages#index', as: :feed
  match ':slug' => 'pages#show', as: :page

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment, :name, :page_id, :url, :email
  belongs_to :page, counter_cache: true

  validates :name, presence: true, length: { in: 2..255 }
  validates :email, presence: true, format: { with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
  validates :url, allow_blank: true, format: { with: URI::regexp(%w(http https)) }
  validates :comment, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::AdminController
  # GET /admin/comments
  # GET /admin/comments.json
  def index
    @comments = Comment.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /admin/comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # PUT /admin/comments/1
  # PUT /admin/comments/1.json
  def update
    @comment = Comment.find(params[:id])
    
    # Clear cache
    PageSweeper.instance.sweep(@comment.page)

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to admin_comments_url, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/comments/1
  # DELETE /admin/comments/1.json
  def destroy
    @comment = Comment.find(params[:id])

    # Clear cache
    PageSweeper.instance.sweep(@comment.page)

    @comment.destroy

    respond_to do |format|
      format.html { redirect_to admin_comments_url, notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  after_filter :prepare_unobtrusive_flash
  cache_sweeper :page_sweeper

  before_filter :authorize, only: [:destroy]

  def create
    page = Page.find(params[:comment][:page_id])

    if params[:remember_me]
      cookies[:comment_name]  = params[:comment][:name]
      cookies[:comment_email] = params[:comment][:email]
      cookies[:comment_url]   = params[:comment][:url]
    end

    # Clear cache
    PageSweeper.instance.sweep(page)

    @comment = page.comments.create params[:comment]
    
    # Send email
    CommentMailer.new_comment(@comment).deliver

    render partial: 'comment', locals: { comment: @comment }
  end

  def destroy
    @comment = Comment.find(params[:id])
    @id = params[:id]

    PageSweeper.instance.sweep(@comment.page)

    @comment.destroy
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_form.html.slim
= simple_form_for [:admin, @comment] do |f|
  - if @comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@comment.errors.count, "error")} prohibited this admin_comment from being saved:"
      ul
        - @comment.errors.full_messages.each do |message|
          li = message
  = f.input :name
  = f.input :email
  = f.input :url
  = f.input :comment
  .actions
    = f.submit 'Save Comment', class: 'btn'
    | &nbsp;
    = link_to 'Back', admin_comments_path

app/views/admin/comments/edit.html.slim
h1 Editing Comment

== render 'form'

app/views/admin/comments/index.html.slim
h1 Listing Comments

table
  tr
    th Post
    th Comment
    th Created
    th.actions colspan="2" Actions

  - @comments.each do |comment|
    tr
      td.vatop = link_to "#{comment.page.title} <i class='icon-external-link'></i>".html_safe, page_path(comment.page.slug), target: '_blank'
      td width="400" = markdown html_escape(comment.comment)
      td.vatop = comment.created_at.to_formatted_s(:short)
      td.vatop.actions.edit = link_to 'Edit', edit_admin_comment_path(comment), class: 'btn'
      td.vatop.actions.delete = link_to 'Destroy', admin_comment_path(comment), :confirm => 'Are you sure?', :method => :delete, class: 'btn'