config/routes.rb
Blog::Application.routes.draw do

  match Blog::CLEAR_CACHE_PATH => 'pages#clear_cache'

  match 'pages/recent_posts' => 'pages#recent_posts'
  match 'pages/:page' => 'pages#index'

  resources :pages
  resources :contact, only: [:create]
  match 'contact' => 'contact#new'

  resources :sessions
  resources :comments, only: [:create, :destroy]
  
  resources :users, only: [:show]

  root :to => 'pages#index'
  
  namespace :admin do
    root to: "pages#index"
    match 'posts' => "pages#index", type: :post
    get 'pages' => "pages#index", type: :page
    resources :pages
    resources :comments
    resources :menus
  end

  match 'login' => 'sessions#new', as: :login
  match 'logout' => 'sessions#destroy', as: :logout

  match 'search' => 'pages#search', as: :search

  match 'archives' => 'pages#archives', as: :archives
  match 'feed' => 'pages#index', as: :feed
  match ':slug' => 'pages#show', as: :page

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :order, :path, :title
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < Admin::AdminController
  # GET /admin/menus
  # GET /admin/menus.json
  def index
    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /admin/menus/1
  # GET /admin/menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /admin/menus/new
  # GET /admin/menus/new.json
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /admin/menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /admin/menus
  # POST /admin/menus.json
  def create
    @menu = Menu.new(params[:admin_menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/menus/1
  # PUT /admin/menus/1.json
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:admin_menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/menus/1
  # DELETE /admin/menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to admin_menus_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/views/admin/menus/_form.html.slim
= form_for @admin_menu do |f|
  - if @admin_menu.errors.any?
    #error_explanation
      h2 = "#{pluralize(@admin_menu.errors.count, "error")} prohibited this admin_menu from being saved:"
      ul
        - @admin_menu.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/admin/menus/edit.html.slim
h1 Editing admin_menu

== render 'form'

= link_to 'Show', @admin_menu
'|
= link_to 'Back', admin_menus_path

app/views/admin/menus/index.html.slim
h1 Listing Menu Items

table
  tr
    th
    th
    th

  - @menus.each do |menu|
    tr
      td = link_to 'Show', menu
      td = link_to 'Edit', edit_admin_menu_path(menu)
      td = link_to 'Destroy', menu, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Menu', new_admin_menu_path

app/views/admin/menus/new.html.slim
h1 New admin_menu

== render 'form'

= link_to 'Back', admin_menus_path

app/views/admin/menus/show.html.slim
p#notice = notice


= link_to 'Edit', edit_admin_menu_path(@admin_menu)
'|
= link_to 'Back', admin_menus_path